### ISSUE TITLE
how to remove a version?

### ISSUE THREAD

**Issue by kalmigs** [noojee/dswitch#4]
Got two stable channel versions, how to remove one? for now I just removed it manually in file explorer.

**Comment by bsutton** [comment]
At this point I hadn't consider an options to remove old versions but it
should really be an option.

In the meantime is preferably safe to remove an old version provided you
don't try to reactivate it.

You can edit the .channel.yaml file in the channel directory to remove the
reference.

**Comment by kalmigs** [comment]
Thanks, didn't see the old version in .channel.yaml. as i already unpinned it.

by the way. I think zip files in .downloads should be removed after installation.

**Comment by bsutton** [comment]
I've added a delete command.

dswitch beta delete <version>

or 

dswitch beta delete --select

I also now delete the zip file after it is expanded.

version 3.3.0
